// SPDX-License-Identifier: GPL-3.0
pragma solidity 0.8.18;


interface IDagoraMembershipsV1 {
  function DAI (  ) external view returns ( address );
  function GRACE_PERIOD (  ) external view returns ( uint256 );
  function _getUpgradePrice ( uint256 tokenId, uint8 oldTier, uint8 newTier ) external view returns ( uint256 _price );
  function _isInitialized (  ) external view returns ( bool );
  function addDelegate ( address _delegatee, uint256 _tokenId ) external;
  function approve ( address to, uint256 tokenId ) external;
  function balanceOf ( address owner ) external view returns ( uint256 );
  function baseURI (  ) external view returns ( string memory );
  function cancelMembership ( uint256 tokenId ) external;
  function claimed ( address ) external view returns ( bool );
  function dagoraRenewPrice (  ) external view returns ( uint256 );
  function dagoraTreasury (  ) external view returns ( address );
  function dagorianPrice (  ) external view returns ( uint256 );
  function discount (  ) external view returns ( uint256 );
  function ecclesiaPrice (  ) external view returns ( uint256 );
  function experation ( uint256 ) external view returns ( uint256 );
  function freeMint (  ) external;
  function getApproved ( uint256 tokenId ) external view returns ( address );
  function getExpereation ( uint256 _tokenId ) external view returns ( uint256 );
  function getMembershipTier ( uint256 _tokenId ) external view returns ( uint8 );
  function getMintPrice ( uint96 _durationInMonths, uint8 _tier ) external view returns ( uint256 _price );
  function getRenewalPrice ( uint96 _newDuration, uint8 currentTier ) external view returns ( uint256 _price );
  function getTokenDelegates ( uint256 _tokenId ) external view returns ( address[] memory );
  function giftExtension ( uint256 tokenId, uint96 durationInMonths ) external;
  function giftMembership ( address to, uint8 tier, uint96 durationInMonths ) external;
  function giftUpgrade ( uint256 tokenId, uint8 tier ) external;
  function hoplitePrice (  ) external view returns ( uint256 );
  function hopliteRenewPrice (  ) external view returns ( uint256 );
  function isApprovedForAll ( address owner, address operator ) external view returns ( bool );
  function isOwnerOrDelegate ( uint256 tokenId, address addrs ) external view returns ( bool _isOwnerOrDelegate );
  function isPaused (  ) external view returns ( bool );
  function isValidMembership ( uint256 _tokenId ) external view returns ( bool );
  function memberships ( uint256 ) external view returns ( uint8 tier, address member, uint256 tokenId, uint256 expiration );
  function mintMembership ( uint96 _durationInMonths, uint8 _tier, uint256 _deadline, uint8 _v, bytes32 _r, bytes32 _s ) external;
  function name (  ) external view returns ( string memory );
  function owner (  ) external view returns ( address );
  function ownerOf ( uint256 tokenId ) external view returns ( address );
  function percelsiaPrice (  ) external view returns ( uint256 );
  function percelsiaRenewPrice (  ) external view returns ( uint256 );
  function removeDelegate ( address _delegatee, uint256 _tokenId, uint8 slot ) external;
  function renewMembership ( uint256 _tokenId, uint256 _deadline, uint96 _durationInMonths, uint8 _v, bytes32 _r, bytes32 _s ) external;
  function renounceOwnership (  ) external;
  function safeTransferFrom ( address from, address to, uint256 tokenId ) external;
  function safeTransferFrom ( address from, address to, uint256 tokenId, bytes calldata _data ) external;
  function setApprovalForAll ( address operator, bool approved ) external;
  function setBaseURI ( string memory _baseURI ) external;
  function setDagoraTreasury ( address _dagoraTreasury ) external;
  function setDagorianPrice ( uint256 _price ) external;
  function setDagorianRenewPrice ( uint256 _price ) external;
  function setDiscount ( uint256 _discount ) external;
  function setEcclesiaPrice ( uint256 _price ) external;
  function setHoplitePrice ( uint256 _price ) external;
  function setHopliteRenewPrice ( uint256 _price ) external;
  function setPercelsiaPrice ( uint256 _price ) external;
  function setPercelsiaRenewPrice ( uint256 _price ) external;
  function supportsInterface ( bytes4 interfaceId ) external view returns ( bool );
  function swapDelegate ( uint256 _tokenId, address oldDelegate, address newDelegate ) external;
  function symbol (  ) external view returns ( string memory );
  function togglePaused (  ) external;
  function tokenDelegates ( uint256, uint256 ) external view returns ( address );
  function tokenURI ( uint256 tokenId ) external view returns ( string memory );
  function totalSupply (  ) external view returns ( uint256 );
  function transferFrom ( address from, address to, uint256 tokenId ) external;
  function transferOwnership ( address newOwner ) external;
  function upgrgadeMembership ( uint8 newTier, uint8 oldTier, uint256 tokenId, uint256 deadline, uint8 v, bytes32 r, bytes32 s ) external;
  function withdrawERC20 ( address _token ) external;
  function withdrawETH (  ) external;
}
